/* eslint-disable @next/next/no-img-element */
import React from "react";
import Link from "next/link";
import { Formik, Form, Field } from "formik";

const PrivacyDetails = () => {
	function validateEmail(value) {
		let error;
		if (!value) {
			error = "Required";
		} else if (!/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(value)) {
			error = "Invalid email address";
		}
		return error;
	}
	const sendComment = (ms) => new Promise((r) => setTimeout(r, ms));
	return (
		<section className="blog-pg single section-padding pt-0">
			<div className="container">
				<div className="row justify-content-center">
					<div className="col-lg-11">
						<div className="post">
							<div className="img">
								{/* <img src="/img/blog/single.jpg" alt="" /> */}
							</div>
							<div className="content pt-20">
								<div className="row justify-content-center">
									<div className="col-lg-10">
										<div className="container">
											<div className="spacial">
												<p>
													These Terms & Conditions (hereinafter referred to as
													the “Terms” or “Terms of Use” or “Terms of Service”)
													shall govern the relationship between Beyin Digital
													Technology Limited, an entity having its registered
													office at FD - Ground Floor, Accelerator Building,
													Masdar City, Abu Dhabi, United Arab Emirates
													(hereinafter referred to the “Company” or “Beyin” or
													“us” or “our” or “we”) and you (hereinafter referred
													to “you” or “your” or “user(s)” or “customer(s)” or
													“client(s)”) and shall also govern your use of
													<span>
														<Link href="www.beyin.me">
															<a className="underline">www.beyin.me/</a>
														</Link>{" "}
													</span>
													(hereinafter individually as well as collectively,
													referred to as the “Website” or “Site”).
												</p>
											</div>
											<p>
												This electronic record is generated by a computer system
												and does not require any physical or digital signatures.
											</p>
											<p>
												Please read these <b>Terms</b> carefully, as these,
												along with our{" "}
												<b>Refund Policy, Shipment Policy, Privacy Policy</b>{" "}
												statement and <b>Cookie Policy</b> forms the entire
												agreement between you and Beyin. If you do not accept
												these Terms in its entirety, then you may not use the
												site or avail our any of our services (including without
												limitation, digital business cards, AR/VR services, web
												application development, software development) or
												purchase our products (including business cards).
											</p>
											<p>
												Additionally, whenever you make a purchase on our
												Website, the same is governed by our{" "}
												<b>Refund Policy</b> and Shipment Policy, and how we
												collect, use, store, share and transmit your data is
												governed by our Privacy Policy statement and{" "}
												<b>Cookie Policy</b>. These Terms & Conditions shall be
												read in conjunction with our <b>Refund Policy</b>,{" "}
												<b>Shipment Policy,</b>
												<b>Privacy Policy</b> statement and <b>Cookie Policy</b>
											</p>
											<div className="spacial" style={{ margin: "50px 0px" }}>
												<ul>
													<li className="ol">
														<h5> Acceptance of the Terms & Conditions</h5>
														<p>
															By accessing or using or registering or availing
															services on our Website in any way or by clicking
															on a button or taking similar action to signify
															your affirmative acceptance of these Terms, you
															hereby represent that:
														</p>
														<ul>
															<li className="liRoman">
																You have read, understood, and agreed to be
																bound by these Terms and any future updates and
																additions to these Terms, as published from time
																to time at the Website.
															</li>
															<li className="liRoman">
																ii. You are of <b>sound mind</b> and at least of
																such minimum <b>legal age</b> as per the
																jurisdiction of the State in which you reside,
																in order to form a binding contract with us.{" "}
																<b className="underline">
																	In case you are not of the age of majority as
																	per the laws of the State that you reside in,
																	then you must have the permission of your
																	lawful guardian to use and access or make
																	purchases on the Website.
																</b>{" "}
															</li>
															<li className="liRoman">
																We must not have previously disabled your
																account for violation of law or any of our
																policies.
															</li>
															<li className="liRoman">
																You have read, understood and consented to our
																<b>Refund Policy</b>, <b>Shipment Policy</b>, as
																well as our <b>Privacy Policy</b> statement and{" "}
																<b>Cookie Policy</b>
															</li>
														</ul>
													</li>
													<li className="ol">
														<h5> Accounts, Passwords and Security</h5>
														<ol>
															<li className="privacy-p liA">
																<b> Account:</b> To access various parts of the
																Website, and to avail various services, you
																might be required to register and create an
																account with us. When setting up and maintaining
																your account, you must provide and continue to
																provide accurate and complete information about
																yourself. As part of the registration process,
																you will create a password and an account.
															</li>
															<li className="privacy-p liA">
																<b>Social Media Signup:</b> You also have an
																option of signing up using social media
																accounts, such as Google and Facebook. In case,
																you chose to sign up using any of the social
																media account, you will be re-directed to the
																website of such social media account, and
																therefore, in addition to these Terms and our
																Privacy Policy, you will also be subject to the
																terms and privacy policy of such social media
																website.{" "}
																<span className="underline">
																	We are not responsible for data collection
																	practices or any other liability arising out
																	of your use of such social media sites.
																</span>
															</li>
															<li className="privacy-p liA">
																<b> Security:</b> You are responsible for
																maintaining the confidentiality of the password
																and account, and are fully responsible for all
																activities that occur under your account,
																including, without limitation, all actions by
																sub-users registered under your account. You
																agree to (a) immediately notify us of any
																unauthorized use of your password or account or
																any other breach of security, and (b) ensure
																that you exit from your account at the end of
																each session. We cannot and will not be liable
																for any loss, damage or other liability arising
																from your failure to comply with this Section or
																from any unauthorized access to or use of your
																account.
															</li>
															<li className="privacy-p liA">
																<b> Inaccurate Information:</b> If we have
																reasonable grounds to suspect that any of the
																information submitted by you is untrue,
																inaccurate, outdated, or incomplete, or that you
																have created a duplicate account, in that case,
																we may terminate your account, and refuse
																current or future use of any or all of the
																services.
															</li>
														</ol>
													</li>
													<li className="ol">
														<h5> Use of the Site</h5>
														<ol>
															<li className="liRoman">
																<b>Allowed uses:</b>
																<ol className="m">
																	<li className="liA ">
																		<b> Directions of Use:</b> You must follow
																		any and all guidelines or policies or
																		directions of use as associated with each of
																		the services on the Site.
																	</li>
																	<li className="liA ">
																		<b> Information:</b> Whenever prompted, you
																		must provide us with the correct, accurate
																		and updated information, including but not
																		limited to your name, business details,
																		website information, billing details,
																		shipping details, email, contact number etc.
																	</li>
																	<li className="liA ">
																		<b>Content of Business Cards:</b> Whenever
																		you submit any content or information or
																		images to be put on your business cards,
																		such content shall be your original and the
																		one that you have the necessary right to
																		use. This content not (without limitation)
																		be illegal, misleading, immoral, harmful,
																		restricted, pornographic, depicting
																		graphical violence or nudity, violative of
																		the intellectual property rights of any
																		third party, sensitive to public or
																		religious sentiments, contrary to law, rule,
																		regulation, notification, judgment, decree
																		or order.{" "}
																		<b className="underline">
																			We reserve the right to not process your
																			order if the content that you submit is
																			violative of these Terms or is against the
																			applicable law, and in such case you will
																			be provided with an opportunity to modify
																			your content.
																		</b>
																	</li>
																	<li className="liA ">
																		<b>Material:</b> For the purposes of these
																		Terms, “material” shall mean any text,
																		video, graphics, animation, effect, sound
																		material, published on the Website or its
																		online app (Extended Business card), whether
																		a copyright of Beyin, its licensors or any
																		third party. You are not allowed to download
																		or print the material, or extracts from it,
																		in a systematic or regular manner or
																		otherwise so as to create a database in
																		electronic or paper form comprising all or
																		part of the material appearing on the
																		Website. You must not reproduce any part of
																		the Website or the material or transmit it
																		to or store it in any other website or
																		disseminate any part of the material in any
																		other form, unless we have indicated that
																		you may do so.
																	</li>
																</ol>
															</li>
															<li className="liRoman">
																{" "}
																<b>Restricted uses:</b>
																<ol className="m">
																	<li className="liA">
																		You can’t impersonate others, create
																		duplicate accounts, or provide inaccurate
																		information.
																	</li>
																	<li className="liA">
																		You cannot use our Site or avail our
																		services or purchase our products for the
																		purpose of resale;
																	</li>
																	<li className="liA">
																		You can’t raise or comment or write review
																		on any political, racist or such other issue
																		which effect’s a person, community or
																		society.
																	</li>
																	<li className="liA">
																		You must not misuse or interfere with the
																		Services or Website or try to access them
																		using a method other than the interface and
																		the instructions that we provide. You may
																		use the Services only as permitted by law
																		and as per the directions provided by us.
																	</li>
																	<li className="liA">
																		<b> You must not:</b>
																		<ol className="m">
																			<li className="liNum">
																				republish material from this Website;
																			</li>
																			<li className="liNum">
																				sell, rent or sub-license material from
																				the Website;
																			</li>
																			<li className="liNum">
																				show any material from the Website in
																				public without our consent;
																			</li>
																			<li className="liNum">
																				edit or otherwise modify any material on
																				the Website (other than editing your own
																				information as per the method provided);
																			</li>
																			<li className="liNum">
																				reproduce, duplicate, copy or otherwise
																				exploit material on our Website for a
																				commercial purpose; or
																			</li>
																			<li className="liNum">
																				redistribute material from the Website,
																				except for content specifically and
																				expressly made available for
																				redistribution with our written consent
																				and according to our terms;
																			</li>
																			<li className="liNum">
																				infringe or violate our Intellectual
																				Property Rights or Intellectual Property
																				Rights of our licensors or any third
																				party
																			</li>
																			<li className="liNum">
																				• We reserve the right to restrict your
																				access to any areas of our Website, or
																				indeed our whole Website, at our
																				discretion.
																			</li>
																		</ol>
																	</li>
																	<li className="liA">
																		You must not use our Website in any way that
																		causes, or may cause, damage to the Website
																		or impairment of the availability or
																		accessibility of the Website; or in any way
																		which is unlawful, illegal, fraudulent or
																		harmful, or in connection with any unlawful,
																		illegal, fraudulent or harmful purpose or
																		activity.
																	</li>
																	<li className="liA">
																		You must not use our Website to copy, store,
																		host, transmit, send, use, publish or
																		distribute any material which consists of
																		(or is linked to) any spyware, computer
																		virus, trojan horse, worm, keystroke logger,
																		rootkit or other malicious computer
																		software.
																	</li>
																	<li className="liA">
																		You must not conduct any systematic or
																		automated data collection activities
																		(including without limitation scraping, data
																		mining, data extraction and data harvesting)
																		on or in relation to our Website, without
																		our express written consent.
																	</li>
																</ol>
															</li>
														</ol>
													</li>
													<div className="quotes text-center">
														In case of your violation or non-compliance of any
														of the terms mentioned in this Terms & Conditions,
														we reserve the right to suspend or terminate your
														account or your access to the Website or our
														services, at our sole discretion.
													</div>

													<li className="ol">
														<h5> Writing a Review or leaving a Feedback</h5>
														<p>
															You may be able to rate your order, share your
															experience and provide a feedback or review for
															such orders. In such case, you shall provide your
															honest and true feedback and opinion. You agree
															not to post anything or perform any act that is
															deemed to be abusive, derogatory, political,
															immoral, unlawful, inappropriate, objectionable,
															or that infringes on ours, or any third-party
															rights.
														</p>
													</li>
													<li className="ol">
														<h5>Ownership Rights</h5>
														<ol className="m">
															<li className="liA">
																<b> Beyin’s Rights:</b> This Website, its app,
																its logos, its content, services, designs,
																animations, trademarks, trade dress, trade name,
																all of our products and services listed on the
																website, shall remain the sole property of the
																Beyin, and/or its licensors, as the case may be.
																Your use of or access to this Website or
																purchase of the products or availing of our
																services shall not in any way transfer or assign
																to you any ownership or other proprietary rights
																in or to this Website, products, services, any
																content, animations, designs, published by us or
																our licensors or third parties. This Website and
																the Content, including but not limited to the
																trademark, logo, copyright, design, layout,
																typography, underlying HTML, Java scripts, text,
																audio clips, video clips and graphics, and in
																the expression of the information contained
																herein, whether as a compilation or otherwise is
																protected by relevant Intellectual Property
																laws, rules and regulations. Trademarks, trade
																names and designs appearing on this Website are
																the exclusive property of, or are licensed to
																the Beyin and are protected.{" "}
																<b className="underline">
																	No use of a trademark, trade dress, trade name
																	or design appearing on this Website may be
																	made without the prior written permission of
																	the Beyin.
																</b>
															</li>
															<li className="liA">
																<h6>Content published by You: </h6>
																<ol className="m">
																	<li className="liRoman">
																		The feedback/review, and information or
																		content that you write or share may be
																		protected by intellectual property laws. You
																		own the intellectual property rights in any
																		such feedback that you share on the Website.
																		Nothing in these Terms takes away the rights
																		you have to your own feedback or content.
																		You are free to share your feedback (except
																		defamatory one) with anyone else, wherever
																		you want.
																	</li>
																	<li className="liRoman">
																		However, to provide our Services we need you
																		to give us some legal permissions (known as
																		a ‘license’) to use this content/feedback of
																		yours. This is solely for the purposes of
																		providing and improving our Services.
																	</li>
																	<li className="liRoman">
																		Specifically, when you share
																		feedback/content that is covered by
																		intellectual property rights, you grant us a
																		non-exclusive, transferable, sub-licensable,
																		royalty-free, and worldwide license to host,
																		use, distribute, modify, copy, publicly
																		perform or display, and translate your
																		content. However, we do not have any
																		responsibility to use or display any part of
																		your feedback on any part of the Website. We
																		retain the right to display the same at our
																		own discretion. For example, if we find it
																		defamatory, misleading or false, we might
																		not display the same
																	</li>
																	<li className="liRoman">
																		You can delete your feedback or your account
																		from our{" "}
																		<b className="underline">Website </b>at any
																		time.
																	</li>
																</ol>
															</li>
														</ol>
													</li>
													<li className="ol">
														<h5>Privacy</h5>
														<p>
															In order to see what{" "}
															<b className="inderline">data</b> we collect and
															how we use or store or share such data, please
															refer to the detailed <b>Privacy Policy </b>
															statement available on our Website.
														</p>
													</li>
													<li className="ol">
														<h5> Links to Third-party Sites </h5>
														<p>
															The Website might contain links to third-party
															websites, products and services. For example, the
															Website works with third party payment service
															providers to provide you the most convenient
															payment options. Such third-party links are not
															under the control of Beyin, and Beyin is not
															responsible for any third-party links. Beyin
															provides access to these third-party links only as
															a convenience to you, and does not review,
															approve, monitor, endorse, warrant, or make any
															representations with respect to third-party links.
															You shall use all third-party links at your own
															risk, and should apply a suitable level of caution
															and discretion in doing so. Whenever you click on
															such links, you are taken to such third-party
															website, and you get out of the jurisdiction of
															our <b className="underline">Website</b>.
															<span className="underline">
																Therefore, you shall be governed by the terms &
																conditions, privacy policy and other policies of
																such third-party websites and we suggest that
																you read those policies.
															</span>{" "}
															In case of any damage due to such action of
															third-party links, Beyin shall not be responsible.
														</p>
													</li>
													<li className="ol">
														<h5> Orders, Payments and Taxes</h5>
														<p>
															All orders are subject to acceptance and you agree
															to pay for the products and services that you
															purchase on our{" "}
															<b className="underline">Website</b>, and you
															authorize us or our third party payment service
															providers to charge your debit or credit card or
															process other means of payment for those payment.
															You shall be responsible to borne all the
															applicable taxes and duties (wherever applicable)
															We reserve the right to modify the prices of our
															products, services or discontinue any of the
															services, at any time at our sole discretion,
															without any prior notice.
														</p>
													</li>
													<li className="ol">
														<h5> Refunds </h5>
														<p>
															We accept the refund requests in limited
															circumstances. To understand this, please refer to
															our detailed <b>Refund Policy</b> available on our
															<b className="underline">Website</b> in order to
															understand when and how we process the refunds.
														</p>
													</li>
													<li className="ol">
														<h5> Disclaimer</h5>
														<p>
															The site and all its products (including business
															cards) and services (including without limitation,
															digital business cards, AR/VR services, web
															application development, software development) are
															provided on an “as-is” and “as available” basis,
															and Beyin (and our licensors and affiliates)
															expressly disclaim any and all warranties and
															conditions of any kind, whether express, implied,
															or statutory, including all warranties or
															conditions of merchantability, fitness for a
															particular purpose, title, quiet enjoyment,
															accuracy, or non-infringement. We (and our
															licensors and affiliates) make no warranty that
															the Site or product or service will meet your
															requirements or likeness, will give you your
															desired look, will increase your profits, will be
															available on an uninterrupted, timely, secure, or
															error-free basis, or will be accurate, reliable,
															free of viruses or other harmful code, complete,
															legal, or safe.{" "}
														</p>
													</li>
													<li className="ol">
														<h5>Limitation of Liability</h5>
														<ol className="m">
															<li className="liA">
																To the maximum extent permitted by law, in no
																event shall Beyin (or our licensors or
																affiliates) be liable to you or any third party
																for any lost profits, lost data, costs of
																procurement of substitute products or services,
																or any indirect, consequential, exemplary,
																incidental, special or punitive damages arising
																from or relating to these terms or your use of,
																or inability to use or purchase from, the site,
																even if Beyin has been advised of the
																possibility of such damages. Access to, and use
																of, the Site is at your own discretion and risk,
																and you will be solely responsible for any
																damage to your device or computer system or
																business, or loss of data resulting therefrom.
															</li>
															<li className="liA">
																To the maximum extent permitted by law,
																notwithstanding anything to the contrary
																contained herein, our liability to you for any
																damages arising from or related to these Terms
																(for any cause whatsoever and regardless of the
																form of the action), will at all times be
																limited to amount of your order in question. The
																existence of more than one claim will not
																enlarge this limit. You agree that our service
																providers, licensors, or affiliates will have no
																liability of any kind arising from or relating
																to these Terms.
															</li>
														</ol>
													</li>
													<li className="ol">
														<h5>Legal Action</h5>
														<p>
															If you are found to be degrading, tarnishing,
															maligning the image, goodwill or reputation of
															Beyin or its affiliates, subsidiaries, or owners,
															by spreading hate, insulting, false, fake reviews
															or engaging in mala fide actions against the
															above, strong legal actions will be taken
															immediately.
														</p>
													</li>
													<li className="ol">
														<h5>Indemnity</h5>
														<p>
															You acknowledge to defend, indemnify and hold
															Beyin, its owners, affiliates, directors,
															officers, employees, agents, partners, and any
															other licensors (hereinafter referred to as
															<b>“Indemnified Party”</b>) harmless from and
															against any claim, disputes, fine, liability,
															demand or expense, including reasonable attorneys’
															fees, made by a third party, relating to, or
															arising from:
														</p>
														<ol className="ma">
															<li className="liA">
																Your violation of ours or any third-party right,
																including without limitation to any right to
																privacy, publicity rights, defamation or
																intellectual property rights;
															</li>
															<li className="liA">
																Your wrongful or improper use of our products,
																services, Site;
															</li>
															<li className="liA">
																Your violation of any applicable laws, rules or
																regulations or any other applicable law through
																or related to the use of our services;
															</li>
															<li className="liA">
																Your violation of these Terms or any other
																policy of Beyin as associated with our services;
															</li>
															<li className="liA">
																The indemnifications set forth above will
																survive the termination or expiration of these
																Terms and/or your use of our services.
															</li>
														</ol>
													</li>
													<li className="ol">
														<h5>Copyright Infringement </h5>
														<ol className="m">
															<li className="liA">
																If we are put on notice that your use, action,
																comment or feedback violates the law or the
																rights of others, or if we discover that your
																content or behaviour is unlawful, inappropriate,
																or objectionable (for example if you impersonate
																someone else or harass them), we may remove your
																feedback from our platform, and/or delete,
																suspend your account from Website .
															</li>
															<li className="liA">
																Please notify us if you believe any of your
																intellectual property rights have been infringed
																on our Website. Please file your copyright
																infringement claim with our Team, at
																<Link href="mailto:support@beyin.me">
																	<a>
																		<span>Email : </span> Support@beyin.me
																	</a>
																</Link>
																for such complaints and claims.
															</li>
															<li className="liA">
																<h6>
																	{" "}
																	You are required to follow the below procedure
																	to file a claim:
																</h6>
																<ol className="ma">
																	<li className="liRoman">
																		Identify in writing the copyrighted material
																		that you claim has been infringed upon;
																	</li>
																	<li className="liRoman">
																		Identify in writing the copyrighted material
																		that has infringed upon your copyright;
																	</li>
																	<li className="liRoman">
																		Provide your current and up-to-date contact
																		information, including your address,
																		telephone number, and e-mail address;
																	</li>
																	<li className="liRoman">
																		Provide your physical and/or electronic
																		signature;
																	</li>
																	<li className="liRoman">
																		Send us a written communication to
																		<Link href="mailto:support@beyin.me">
																			<a>
																				<span>Email : </span> Support@beyin.me
																			</a>
																		</Link>
																		;
																	</li>
																	<li className="liRoman">
																		You may be subject to liability if you
																		knowingly make any misrepresentations on a
																		take-down notice or claim.
																	</li>
																</ol>
															</li>
														</ol>
													</li>
													<li className="ol">
														<h5>Governing Law and Dispute Resolution</h5>
														<ol className="m">
															<li className="liRoman">
																<b> Governing Law:</b> The Terms and any dispute
																arising from the same will be governed by
																applicable laws of{" "}
																<b>United Arab Emirates (UAE)</b>.
															</li>
															<li className="liRoman">
																<b>Exclusive Jurisdiction:</b> All disputes must
																first be attempted to resolved amicably, failing
																which, such controversy, conflict or dispute
																shall be finally settled by bringing it before
																the appropriate courts located in{" "}
																<b> Abu Dhabi</b>, <b>UAE</b>.
															</li>
															<li className="liRoman">
																<b> Applicable Statute:</b> The above-mentioned
																governing law and jurisdiction shall only apply
																to you unless the contrary has not been provided
																by the relevant statute, rules or directives
																applicable to the jurisdiction in which you
																reside. However, if the statute, rule or
																directive prevailing in the jurisdiction that
																you reside in provides for a different governing
																law and dispute resolution mechanism, in that
																case you are well within your rights to exercise
																the same.
															</li>
														</ol>
													</li>
													<li className="ol">
														<h5>Notices</h5>
														<p>
															When you use the Website or send emails to Beyin,
															you are communicating with us electronically. You
															consent to receive electronically any
															communications related to your use of this
															Website. Beyin will communicate with you by email
															or phone or WhatsApp or by posting notices on this
															Website. You agree that all agreements, notices,
															disclosures and other communications that are
															provided to you electronically satisfy any legal
															requirement that such communications be in
															writing. We may give notice by means of a general
															notice via electronic mail to your email address
															or phone number or SMS or WhatsApp as available
															with us. If You want to give a notice to us, you
															can do so by dropping an electronic mail to
															<Link href="mailto:support@beyin.me">
																<a>
																	<span>Email : </span> Support@beyin.me
																</a>
															</Link>
														</p>
													</li>
													<li className="ol">
														<h5>Miscellaneous</h5>
														<ol className="m">
															<li className="liRoman">
																<b> Severability:</b> If any provision of these
																Terms is held to be unenforceable or invalid,
																such provision will be changed and interpreted
																to accomplish the objectives of such provision
																to the greatest extent possible under applicable
																law and the remaining provisions of these Terms
																will continue in full force and effect.
															</li>
															<li className="liRoman">
																<b>Waiver:</b> Our failure to insist on or
																enforce strict performance of these Terms &
																Conditions shall not be construed as a waiver by
																us of any provision or any right that we have to
																enforce these Terms and nor shall any course of
																conduct between Beyin and you or any other party
																be deemed to modify any provision of these
																Terms.
															</li>
															<li className="liRoman">
																<b> Survival:</b> Notwithstanding any other
																provisions of these Terms & Conditions, or any
																general legal principles to the contrary, any
																provision of these Terms & Conditions that
																imposes or contemplates continuing obligations
																on either party shall survive the expiration or
																termination of these Terms & Conditions, for any
																reason whatsoever.
															</li>
															<li className="liRoman">
																<b>No Third-Party Beneficiaries:</b> Except as
																otherwise expressly provided in these Terms &
																Conditions, there shall be no third-party
																beneficiaries to these Terms & Conditions.
															</li>
															<li className="liRoman">
																<b> No Assignment:</b> You may not assign these
																Terms & Conditions (or any rights, benefits or
																obligations hereunder) by operation of law or
																otherwise without the prior written consent of
																Beyin, which may be withheld at Beyin’s sole
																discretion. Any attempted assignment that does
																not comply with these Terms & Conditions shall
																be null and void.
															</li>
															<li className="liRoman">
																<b>Entire Agreement:</b> The{" "}
																<b>Terms, Refund Policy</b>,{" "}
																<b>Shipment Policy</b>,
																<b> our Privacy Policy</b> as well as our{" "}
																<b>Cookie Policy</b>, together with any
																additional terms and conditions incorporated
																herein or referred to herein constitute the
																entire Agreement between Beyin and you, relating
																to the subject matter hereof, and supersedes any
																prior understanding or agreements (whether oral
																or written) regarding the subject matter, and
																may not be amended or modified except in writing
																or by making such amendments or modifications
																available on our Website.
															</li>
															<li className="liRoman">
																<b>Force Majeure:</b> Beyin, its employees,
																contractors, and its third party delivery
																service providers will be excused from
																performance for any period during which, and to
																the extent that, such party or any subcontractor
																is prevented from performing any obligation or
																service (such as processing or shipment or
																delivery of your order), in whole or in part, as
																a result of causes beyond its reasonable
																control, and without its fault or negligence,
																including without limitation, acts of God,
																strikes, lockouts, riots, acts of terrorism or
																war, epidemics, communication line failures,
																power failures and government-imposed lockdowns
																or similar restrictions.
															</li>
															<li className="liRoman">
																<b> Updates to these Terms:</b> We may add to or
																change or update these Terms at any time, from
																time to time, entirely at our own discretion,
																with or without any prior written notice. You
																are responsible for checking these Terms
																periodically. Your use of the Site after any
																amendments to the Terms shall constitute your
																acceptance to such amendments.
															</li>
														</ol>
													</li>
													<li className="ol">
														<h5>Grievance Officer/Designated Representative</h5>
														<p>
															In the event you have any grievance regarding
															anything related to these{" "}
															<b>
																Terms or Refund Policy or Shipment Policy or
																Privacy Policy or Cookie Policy
															</b>
															, or with any content or service or product of
															Beyin, in that case you may freely write your
															concerns registered email to{" "}
															<Link href="mailto:support@beyin.me">
																<a>
																	<span>Email : </span> Support@beyin.me
																</a>
															</Link>
														</p>
													</li>
													<li className="ol">
														<h5>Feedback and Information</h5>
														<p>
															We welcome your questions or comments regarding
															the Terms. You can write to us via email:
															<Link href="mailto:support@beyin.me">
																<a>
																	<span>Email : </span> Support@beyin.me
																</a>
															</Link>
														</p>
													</li>
												</ul>
												<p className="underline">Last updated on 7/17/2022.</p>
											</div>

											{/* <div className="row">
												<div className="col-md-6">
													<div className="mb-10">
														<img src="/img/blog/single.jpg" alt="" />
													</div>
												</div>
												<div className="col-md-6">
													<div className="mb-10">
														<img src="/img/blog/single.jpg" alt="" />
													</div>
												</div>
											</div> */}
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	);
};

export default PrivacyDetails;

{/* <li style={{ margin: "30px 0px" }}>

													</li> */}